//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageBeheerder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class knowledge
    {
        public knowledge()
        {
            this.internships = new HashSet<internships>();
            this.teachers = new HashSet<teachers>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<internships> internships { get; set; }
        public virtual ICollection<teachers> teachers { get; set; }
    }
}
