//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrators
    {
        public administrators()
        {
            this.education = new HashSet<education>();
        }
    
        public int user_id { get; set; }
        public string password { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<education> education { get; set; }
    }
}
