//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbstageview
    {
        public Nullable<int> sr { get; set; }
        public long internshipID { get; set; }
        public string description { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime creation_date { get; set; }
        public string type { get; set; }
        public string feedback { get; set; }
        public string approved { get; set; }
        public string achieved { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string phonenumber { get; set; }
        public Nullable<int> teachID { get; set; }
        public string teachernumber { get; set; }
        public string teacher_name { get; set; }
        public string teacher_surname { get; set; }
        public string teacher_email { get; set; }
        public string teacher_phonenumber { get; set; }
        public string sv_name { get; set; }
        public string sv_surname { get; set; }
        public string sv_email { get; set; }
        public string sv_phonenumber { get; set; }
        public string education { get; set; }
        public string function { get; set; }
        public int minimal_time { get; set; }
        public string company_name { get; set; }
        public int address_id { get; set; }
        public string company_phonenumber { get; set; }
        public string website { get; set; }
    }
}
