//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public students()
        {
            this.students_internships = new HashSet<students_internships>();
        }
    
        public int user_id { get; set; }
        public int studentnumber { get; set; }
        public int education_id { get; set; }
        public Nullable<int> addresss_id { get; set; }
    
        public virtual adresses adresses { get; set; }
        public virtual education education { get; set; }
        public virtual ICollection<students_internships> students_internships { get; set; }
        public virtual users users { get; set; }
    }
}
