//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentadress
    {
        public int user_id { get; set; }
        public int studentnumber { get; set; }
        public int education_id { get; set; }
        public Nullable<int> addresss_id { get; set; }
        public int id { get; set; }
        public string place { get; set; }
        public string street { get; set; }
        public string housenumber { get; set; }
        public string zipcode { get; set; }
    }
}
