//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers
    {
        public teachers()
        {
            this.internships = new HashSet<internships>();
            this.volumehours = new HashSet<volumehours>();
            this.internships1 = new HashSet<internships>();
            this.education = new HashSet<education>();
            this.knowledge = new HashSet<knowledge>();
        }
    
        public int user_id { get; set; }
        public string teachernumber { get; set; }
        public int transport_id { get; set; }
        public int address_id { get; set; }
    
        public virtual adresses adresses { get; set; }
        public virtual ICollection<internships> internships { get; set; }
        public virtual transport transport { get; set; }
        public virtual users users { get; set; }
        public virtual ICollection<volumehours> volumehours { get; set; }
        public virtual ICollection<internships> internships1 { get; set; }
        public virtual ICollection<education> education { get; set; }
        public virtual ICollection<knowledge> knowledge { get; set; }
    }
}
