//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class volumehours
    {
        public int teacher_user_id { get; set; }
        public int year { get; set; }
        public Nullable<int> remaining_hours1 { get; set; }
        public Nullable<int> remaining_hours2 { get; set; }
        public Nullable<int> remaining_hours3 { get; set; }
        public Nullable<int> remaining_hours4 { get; set; }
    
        public virtual teachers teachers { get; set; }
    }
}
