//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageBeheerder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_internships
    {
        public long intership_id { get; set; }
        public int student_user_id { get; set; }
        public string achieved { get; set; }
    
        public virtual internships internships { get; set; }
        public virtual students students { get; set; }
    }
}
