//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageBeheerder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webkeys
    {
        public string webkey { get; set; }
        public Nullable<int> user_id { get; set; }
        public string type { get; set; }
        public string email { get; set; }
    
        public virtual users users { get; set; }
    }
}
